# Generated by Django 5.2.7 on 2026-05-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplaceuser',
            options={},
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='publication_deleted_8ba828_idx',
            old_name='marketplace_deleted_0fb178_idx',
        ),
        migrations.RenameIndex(
            model_name='publication',
            new_name='publication_categor_848de0_idx',
            old_name='marketplace_categor_b62bd1_idx',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='marketplaceuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='publications',
        ),
    ]
