# Generated by Django 5.2.7 on 2026-05-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_marketplaceuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='summary',
        ),
    ]
