# Generated by Django 6.0.5 on 2026-05-24 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_publication_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='location',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de Mexico', 'Ciudad de Mexico'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de Mexico', 'Estado de Mexico'), ('Michoacan', 'Michoacan'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Leon', 'Nuevo Leon'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Queretaro', 'Queretaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosi', 'San Luis Potosi'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatan'), ('Zacatecas', 'Zacatecas')], max_length=120),
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='publications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.publication')),
            ],
        ),
    ]
